from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
print("test case started")
driver = webdriver.Chrome()
driver.maximize_window()
driver.delete_all_cookies()
driver.get("http://secure.smartbearsoftware.com/samples/testcomplete11/WebOrders/login.aspx")
driver.find_element_by_id("ctl00_MainContent_username").send_keys("Tester")
driver.find_element_by_id("ctl00_MainContent_password").send_keys("test")
driver.find_element_by_id("ctl00_MainContent_login_button").click()
time.sleep(2)
driver.find_element_by_id("ctl00_MainContent_btnCheckAll").click()
time.sleep(2)
driver.find_element_by_id("ctl00_MainContent_btnUncheckAll").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/form/table/tbody/tr/td[1]/ul/li[2]/a").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/form/table/tbody/tr/td[1]/ul/li[3]/a").click()
driver.find_element_by_id("ctl00_MainContent_fmwOrder_txtQuantity").send_keys("3")
driver.find_element_by_xpath("/html/body/form/table/tbody/tr/td[2]/div[2]/table/tbody/tr/td/ol[1]/li[5]/input[2]").click()
time.sleep(2)
driver.find_element_by_id("ctl00_MainContent_fmwOrder_txtName").send_keys("chandana")
driver.find_element_by_id("ctl00_MainContent_fmwOrder_TextBox2").send_keys("abc")
driver.find_element_by_id("ctl00_MainContent_fmwOrder_TextBox3").send_keys("thrissur")
driver.find_element_by_id("ctl00_MainContent_fmwOrder_TextBox4").send_keys("kerala")
driver.find_element_by_id("ctl00_MainContent_fmwOrder_TextBox5").send_keys("680026")
time.sleep(2)

driver.find_element_by_id("ctl00_MainContent_fmwOrder_cardList_1").click()
driver.find_element_by_id("ctl00_MainContent_fmwOrder_TextBox6").send_keys("5678903454")
driver.find_element_by_id("ctl00_MainContent_fmwOrder_TextBox1").send_keys("12/22")
time.sleep(2)
driver.find_element_by_id("ctl00_MainContent_fmwOrder_InsertButton").click()
time.sleep(2)

driver.find_element_by_id("ctl00_logout").click()
time.sleep(2)
driver.close()
print("successfully completed")
